### ISSUE TITLE
文面変更 /reply

### ISSUE THREAD

**Issue by yoshi522** [manma-co/kazoku-db-system#102]
#### 変更 1
変更前: 実施予定日で指定された時間の中で記入してください。
変更後: 実施予定日で指定された時間の中で５時間以上の長さで記入してください。

#### 変更 2
待ち合わせ場所（駅・出口）の下に注意書きをかく
文面: できるだけ詳しく記入してください。

#### 変更 3
変更前: これまでに家族留学にいった経験はありますか？
変更後: これまでに家族留学を受け入れた経験はありますか？

#### 変更 4
変更前: 上記質問で〜
変更後: 受け入れのない方への質問です。電話面談（10分）が可能な候補日時を3つ教えてください。

**Comment by RyutaroFukuma** [comment]
**変更5**
変更前: この家族留学の問い合わせに対して確約をする'
変更後: 家族留学の受け入れを確定する
