### ISSUE TITLE
ご家庭にメールを一斉送信する機能

### ISSUE THREAD

**Issue by harhogefoo** [manma-co/kazoku-db-system#110]
メルマガではなく、連絡をしたい場合に一括送信

- [ ] メール送信機能: 高柴
- [ ] 受信設定のページを作成: 高柴

**Comment by yoshi522** [comment]
必要項目

- 送信日時
- タイトル
- 本文

**Comment by yoshi522** [comment]
メール送信機能は #81 と共通。

- [ ]  受信設定のページを作成とその設定をリンクにしてメールに加える。
- [ ]  indexページの作り込み
- [ ]  new のエンハンス
- [ ]  showの作成
