### ISSUE TITLE
受け入れ確定ボタン押下後の遷移先でエラーが出る

### ISSUE THREAD

**Issue by RyutaroFukuma** [manma-co/kazoku-db-system#134]

**Comment by harhogefoo** [comment]
一旦スプレッドシートから情報を取得
を実行してからもう一回試してみて

**Comment by RyutaroFukuma** [comment]
同じエラーでますねー

**Comment by harhogefoo** [comment]
https://developers.google.com/api-client-library/ruby/auth/service-accounts
これ使って実装すればよかったんやー、、
