### ISSUE TITLE
メール送信機能のベーシックな設定。

### ISSUE THREAD

**Issue by yoshi522** [manma-co/kazoku-db-system#18]
smtpかsparkpost.

- [x] 家族への問い合わせメール / 家族向け
- [x] Transaction table を作成
- [x] メールの送信履歴ページを作成
- [x] メールリクエスト成立させるページ
- [x] 各ユーザーへのリクエストログが欲しい(送信履歴とは別に、拒否したかどうかを判断するため）
- [x] マッチング成立時のメール / 家族向け
- [x] マッチング成立時のメール / 参加者向け

**Comment by yoshi522** [comment]
herokuで動かすときに下記コマンドが必要。
```
heroku addons:create sendgrid:starter
```

**Comment by yoshi522** [comment]
・希望日程
・学生氏名
・所属
・希望理由
を記述しておく。（メールに記載したもの）

**Comment by yoshi522** [comment]
はい、いいえボタンをクリックさせて、
はいの場合は
 - 開始時間（選択式 -> 選択後、編集可能にする）
 - 集合場所
 - 備考
 - 緊急連絡先
 - 家族留学が初めてかどうかを聞く（備考として電話しますと記述）


その後家庭・参加者に対して、メールを送る。

＜参加者向け＞
家庭情報から引っ張ってくるもの
・電話番号
・日時 
・集合場所
・開始時刻 / 終了時刻
・家庭の情報 （家族構成 / 名前）
・manmaの顧客窓口連絡先

＜家庭向け＞
・受け入れのお礼
・日時 
・集合場所
・開始時刻 / 終了時刻
・学生の情報 （名前  / 所属）
 ・manmaの顧客窓口連絡先

**Comment by yoshi522** [comment]
３日経っても誰も受け入れOKがない場合　ー＞　未回答の家庭にリマインド送信

７日経っても「はい」がない場合 or 全員が拒否した場合、info@manma.coから
学生に再打診の希望を尋ねるメールを送る

**Comment by harhogefoo** [comment]
リマインド機能は別issueが立っているのでcloseしてしまって問題なければcloseしてくださいー！
@yoshi522
