### ISSUE TITLE
本番環境のインスタンスを作成。

### ISSUE THREAD

**Issue by yoshi522** [manma-co/kazoku-db-system#20]

**Comment by yoshi522** [comment]
インスタンスの中身をゴリゴリ設定すると時間的に辛いので、Cloud Launcher でサクッと作るのが良さそう。
App Engine 1 インスタンスなら無料枠におさまるが、拡張すると高い（１インスタンスあたり$30）のでCloud Launcherでやってみよう。（$5 / month)

**Comment by harhogefoo** [comment]
7月からの家族DBシステムの運用なんだけどGCP使わずにherokuでやってしまっても問題ないかなーとか思ったんだけど何か思うところがあったら教えて欲しい！

**Comment by yoshi522** [comment]
おれもそう思った！
Cloud SQL -> ちょっと高い
GCE -> 設定が大変（セキュリティ的にも）

Herokuはアカウントにインスタンスが１つだけであればずっと起こしてられるから curl で叩き起こし続けるのもありかも。UXが気になるのであれば。

**Comment by yoshi522** [comment]
必要ないのでclose
