### ISSUE TITLE
駅すぱあとAPIの調査実装

### ISSUE THREAD

**Issue by RyutaroFukuma** [manma-co/kazoku-db-system#49]
https://ekiworld.net/service/lp/webservice/

**Comment by harhogefoo** [comment]
フリープランだと駅すぱあとwebのURLが返ってくるので、もし実装をするならスクレイピングするような処理が必要
なお有料プランならjsonで情報が返ってくるので実装しすくはなる。

スクレイピングをする工数を考慮すると実装は厳しいかな。。閉じます。
