### ISSUE TITLE
secrets.yml内に記述してあるキーを環境変数に置き換える（その前にコミットログを削除する？）

### ISSUE THREAD

**Issue by harhogefoo** [manma-co/kazoku-db-system#51]
リリース前にはやりたい

**Comment by harhogefoo** [comment]
何処かにsecrets.ymlをおいておく場所を作らないといけないな

**Comment by yoshi522** [comment]
https://railsguides.jp/4_1_release_notes.html#config-secrets-yml
https://railsguides.jp/upgrading_ruby_on_rails.html#config-secrets-yml
この上二つにもsecrets.ymlを隠しなさいとは書いていないのと、

https://github.com/search?utf8=%E2%9C%93&q=rails++heroku&type=Repositories
herokuにdeployしているアプリはsecrets.ymlがあるのがほとんなのと

```
# Do not keep production secrets in the repository,
# instead read values from the environment.
```
secrets.ymlには「環境変数から呼びなさい」と書いてあるだけなので
消す必要はないんじゃないかと思う。
セキュリティ的な問題はないかと・・・
基本的にsecrets.ymlがないと運用できないからローカルにsecrets.ymlを持っておけばよいが
herokuを使う場合はgitでdeployするから、secrets.ymlもgitに含めないといけない。
よってsecrets.ymlは抹消できない！と思います！

**Comment by harhogefoo** [comment]
@yoshi522 参考文献ありがとう！なるほどです。secrets.ymlを消す方針ではなく、screts.yml内に記述してあるキーを環境変数に置き換えることにしますか！

**Comment by harhogefoo** [comment]
あ、ただ過去のコミットログに昔の情報が残ってしまうのでやはり一度コミットログを抹消してから環境変数に置き換えたものをコミットする必要がありそう

**Comment by yoshi522** [comment]
sparkpostの問題ですね。お願いします！

**Comment by yoshi522** [comment]
sparkpostの問題ないかも。本番で使ってないし、フリーのものなので。

**Comment by harhogefoo** [comment]
検討ありがとう
