### ISSUE TITLE
家族情報詳細ページで無駄な読み込みが発生している可能性

### ISSUE THREAD

**Issue by harhogefoo** [manma-co/kazoku-db-system#52]
表示するデータごとにfind_byを呼び出してるのはあまりよくないかも
ActiveRecordのキャッシュが自動で聞いてくれているので現状の実装でも問題ないが事前にロードしておく実装のほうがいいと思う。

家族詳細ページに実行されている様子のスクリーンショット
<img width="1532" alt="2017-05-14 1 12 47" src="https://cloud.githubusercontent.com/assets/11906529/26027112/b5df80a4-3842-11e7-9b2a-756c96bd3665.png">

**Comment by RyutaroFukuma** [comment]
事前にロードしておくよう実装しました
![2017-05-18 16 12 08](https://cloud.githubusercontent.com/assets/23731635/26190799/4569b7f2-3be6-11e7-8caf-01588ac3c86b.png)
