### ISSUE TITLE
unicorn.rbの導入

### ISSUE THREAD

**Issue by hidetomasuoka** [manma-co/kazoku-db-system#53]
https://github.com/manma-co/kazoku-db-system/blob/master/config/environments/production.rb

host名とかべた書きなので、修正したほうがよさそう

**Comment by yoshi522** [comment]
```
Heroku recommends using the Puma web server instead of Unicorn. If you are using Unicorn, your application is not protected against a slow client attack.
```

https://devcenter.heroku.com/articles/rails-unicorn
