### ISSUE TITLE
Copyrightを発行年にする

### ISSUE THREAD

**Issue by hidetomasuoka** [manma-co/kazoku-db-system#54]
- 先頭の「Copyright」はいらない
- 更新の年号はあってもなくてもOK
- 最初の発行年は必要な要素
- 「All Rights Reserved」は一番いらない要素

https://liginc.co.jp/designer/archives/11313

アップデートのコストも考えると発行年だけあればよいと思う

**Comment by hidetomasuoka** [comment]
古いコミットをみてました。失礼しました

**Comment by harhogefoo** [comment]
ありがとうございます mm
