### ISSUE TITLE
打診メール本文修正

### ISSUE THREAD

**Issue by harhogefoo** [manma-co/kazoku-db-system#59]
- [x] メールの文頭にBCCでお送りしています を追加位 
- [ ] 受け入れ家庭の名前を表示 ex) xx 様 <- 高柴のタスク
- [ ] 個人情報に関するお断りをメールの末尾に追加する
- [ ] 返信フォーマット内に特記事項を追加

細かい文面は以下のURL
https://docs.google.com/document/d/1mr65u1QYhV6r4qxS19q-NpbEXliC-nM593LOhOEbl2g/edit

**Comment by RyutaroFukuma** [comment]
@harhogefoo 
受け入れ家庭の名前を表示 ex) xx 様
ってあるけど、家庭複数選んだ場合どうなる
メール側の動き変わるんだっけ？

**Comment by yoshi522** [comment]
これメール側で処理します！！

**Comment by yoshi522** [comment]
@harhogefoo 
これ、bccで一斉送信しているので難しいですね。
分けて送るようにしますか？

**Comment by harhogefoo** [comment]
@yoshi522 今回の要件で名前を入れてほしいとのことなので、分けるしかなさそうですね。。
メール送信の上限数まで行かなければ、分ける実装で大丈夫だと思います！

**Comment by yoshi522** [comment]
了解ですー！
conflict を防ぐため、request_log ブランチのマージ後に実装します！

**Comment by harhogefoo** [comment]
Thanks
