### ISSUE TITLE
回答URL先のViewのデザインを整える

### ISSUE THREAD

**Issue by harhogefoo** [manma-co/kazoku-db-system#68]
#63 完了次第作業開始

レスポンシブ対応
- [x] Bootstrapを導入するのが最短だと思う。
- [x] 回答URLをクリックしたときのページデザイン
- [x] 受け入れるをクリックしたときのページデザイン
- [x] 確約をクリックしたときのページデザイン
- [x] すでに他の家庭とのマッチングが成立しています。次の機会にどうぞよろしくお願いします。のページデザイン（URL: /sorry)
- [x] 家族留学受け入れ不可の場合のページデザイン(URL: /deny)

**Comment by RyutaroFukuma** [comment]
request以下に対してbootstrap適用できず、詰まってます
