### ISSUE TITLE
月に1回学生会員にリマインドメールを送信

### ISSUE THREAD

**Issue by harhogefoo** [manma-co/kazoku-db-system#81]
- [x] 取得するスプレッドシートの確定 : 新居
- [x] スプレッドシートから情報取得 : 篠原
- [x] 学生用モデルの定義：篠原
- [x] ニュースレター画面作成、設定：高柴
- [x] 受信設定のページを作成：高柴

必要な情報は
氏名、メールアドレス、電話番号

**Comment by harhogefoo** [comment]
@yoshi522 学生情報の取得部分をfixしました。ニュースレター機能お願いしますmm

**Comment by yoshi522** [comment]
ニュースレター画面作成はほぼ完了
